[package]
name = "mkp"
version = "0.1.0"
authors = ["Nouzan <clobraindie@outlook.com>"]
edition = "2018"

[dependencies]
clap-verbosity-flag = "0.3"
structopt = "0.3"
log = "0.4"
simplelog = { version = "0.8" }
anyhow = "1.0"
serde = { version="1.0", features = ["derive"] }
toml = "0.5"
